slides.pdf: slides.tex aaltoslides.cls Makefile Aalto_EN_ScienceandTech_13_RGB_b3.pdf Aalto_EN_ScienceandTech_21_RGB_b3.pdf
	pdflatex slides
	pdflatex slides

clean:
	rm -f *.aux *.log *.bbl *.blg *.dvi *.toc *.snm *.out *.nav
